import { useRef, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Printer, Copy, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface ExportButtonProps {
  /** Ref to the container element whose content should be exported */
  targetRef: React.RefObject<HTMLElement>;
  title?: string;
}

export function ExportButton({ targetRef, title }: ExportButtonProps) {
  const { toast } = useToast();

  const handlePrint = useCallback(() => {
    const el = targetRef.current;
    if (!el) return;

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast({ title: 'Pop-up blocked', description: 'Please allow pop-ups to print.', variant: 'destructive' });
      return;
    }

    const timestamp = new Date().toLocaleString();
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title || 'Calculator Results'}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 24px; color: #1a1a1a; }
          .header { border-bottom: 2px solid #333; padding-bottom: 12px; margin-bottom: 16px; }
          .header h1 { font-size: 18px; font-weight: 700; }
          .header p { font-size: 11px; color: #666; margin-top: 4px; }
          .content { font-size: 13px; line-height: 1.6; }
          .content table { border-collapse: collapse; width: 100%; margin: 8px 0; }
          .content th, .content td { border: 1px solid #ccc; padding: 4px 8px; text-align: left; font-size: 12px; }
          .content th { background: #f5f5f5; font-weight: 600; }
          .footer { margin-top: 24px; padding-top: 12px; border-top: 1px solid #ccc; font-size: 10px; color: #999; }
          svg { display: none !important; }
          button { display: none !important; }
          input, select, textarea { border: none !important; background: transparent !important; padding: 0 !important; font-size: 12px; }
          [data-radix-collection-item] { display: none !important; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title || 'Calculator Results'}</h1>
          <p>Exported: ${timestamp}</p>
        </div>
        <div class="content">${el.innerHTML}</div>
        <div class="footer">Generated by Process Tools — ${timestamp}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 300);
  }, [targetRef, title, toast]);

  const handleCopyText = useCallback(() => {
    const el = targetRef.current;
    if (!el) return;

    const text = el.innerText;
    const header = title ? `${title}\n${'='.repeat(title.length)}\n` : '';
    const footer = `\n---\nExported: ${new Date().toLocaleString()}`;

    navigator.clipboard.writeText(header + text + footer).then(() => {
      toast({ title: 'Copied to clipboard', description: 'Calculator results copied as text.' });
    }).catch(() => {
      toast({ title: 'Copy failed', description: 'Could not copy to clipboard.', variant: 'destructive' });
    });
  }, [targetRef, title, toast]);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-1.5">
          <Download className="h-3.5 w-3.5" />
          <span className="hidden sm:inline">Export</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handlePrint}>
          <Printer className="h-4 w-4 mr-2" />
          Print / Save PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleCopyText}>
          <Copy className="h-4 w-4 mr-2" />
          Copy as Text
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}

/**
 * Hook to easily add export functionality to any calculator.
 * Returns a ref to attach to the card, and the ExportButton component.
 */
export function useExport(title: string) {
  const ref = useRef<HTMLDivElement>(null);
  const ExportBtn = () => <ExportButton targetRef={ref} title={title} />;
  return { ref, ExportBtn };
}
